name: Auto-Sync Cursor & Replit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  sync-replit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Push Changes to Replit
        run: |
          git remote add replit https://your-replit-git-url.git
          git push replit main --force
